[package]
name = "pin-project-internal"
# NB: When modifying, also modify html_root_url in lib.rs
version = "0.3.4"
authors = ["Taiki Endo <te316e89@gmail.com>"]
edition = "2018"
license = "Apache-2.0/MIT"
description = "An interal crate to support pin_project - do not use directly"
repository = "https://github.com/taiki-e/pin-project"
documentation = "https://docs.rs/pin-project/"
readme = "README.md"
keywords = ["pin", "macros", "attribute"]
categories = ["rust-patterns"]
exclude = ["/.travis.yml", "/bors.toml"]

[lib]
proc-macro = true

[features]
# Default features.
default = ["project_attr"]
# Enable to use `project` attribute.
project_attr = ["syn/visit-mut"]


[dependencies]
proc-macro2 = "0.4.13"
quote = "0.6.8"
syn = { version = "0.15.29", features = ["full", "extra-traits"] }
proc-macro-crate = "0.1.4"
# Required until https://github.com/alexcrichton/toml-rs/pull/311 is merged,
# and proc-macro-crate updates to a new version of toml-rs
serde = "1.0.97"
lazy_static = "1.3.0"
