[package]
name = "pin-project"
version = "0.4.0-alpha.1"
authors = ["Taiki Endo <te316e89@gmail.com>"]
edition = "2018"
license = "Apache-2.0/MIT"
repository = "https://github.com/taiki-e/pin-project"
documentation = "https://docs.rs/pin-project/"
readme = "README.md"
keywords = ["pin", "macros", "attribute"]
categories = ["rust-patterns"]
description = "A crate for safe and ergonomic pin-projection."

[package.metadata.docs.rs]
all-features = true

[workspace]
members = ["pin-project-internal"]

[features]
# Enable to use `project` attribute.
project_attr = ["pin-project-internal/project_attr"]
# Enable to allow using this crate as a renamed dependency
renamed = ["pin-project-internal/renamed"]

[dependencies]
pin-project-internal = { version = "=0.4.0-alpha.1", path = "pin-project-internal", default-features = false }

[dev-dependencies]
compiletest = { version = "0.3.21", package = "compiletest_rs", features = ["stable", "tmp"] }
